image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - ms-vscode.cpptools@1.1.0-insiders2:ewjLo4MUP0CjrimwKlYsBg==
    - hansec.fortran-ls@0.6.2:lG2VHpMxRQoC1jys0VI0yA==
    - VisualStudioExptTeam.vscodeintellicode@1.2.2:VyaPhtK5JDcrioOPwlZlsw==
    - krvajalm.linter-gfortran@2.2.1:9CJIQJ84TaIZY3KC4zm+lQ==
